// import emojis from 'emojis-list';

export default [
    {
        name: 'Numbers',
        description: 'Match numbers.  Uses no extra bandwidth.',
        credit: null,
        cover: 'img/numbers.png',
        url: null,
        images: null
    },
    {
        name: 'Emoji',
        description: 'Match Emoji Characters.',
        credit: null,
        cover: 'img/emoji.png',
        url: null,
        images: null,
        chars: async () => {
            const pkg = await import(/* webpackChunkName: "emoji" */ 'emojis-list');
            return pkg.default;
        }
    },
    {
        name: 'Super Smash Bros.',
        description: 'Super Smash Brothers',
        credit: 'Super Mario Wiki',
        url: 'http://www.mariowiki.com/',
        cover: 'img/ssb/mario.png',
        images: [
            'img/ssb/bowser.png',
            'img/ssb/captain.png',
            'img/ssb/diddy.png',
            'img/ssb/dk.png',
            'img/ssb/drmario.png',
            'img/ssb/falco.png',
            'img/ssb/fox.png',
            'img/ssb/gamewatch.png',
            'img/ssb/ganondorf.png',
            'img/ssb/jigglypuff.png',
            'img/ssb/kirby.png',
            'img/ssb/link.png',
            'img/ssb/luigi.png',
            'img/ssb/mario.png',
            'img/ssb/marth.png',
            'img/ssb/metaknight.png',
            'img/ssb/mewtwo.png',
            'img/ssb/ness.png',
            'img/ssb/peach.png',
            'img/ssb/pikachu.png',
            'img/ssb/pit.png',
            'img/ssb/rob.png',
            'img/ssb/roy.png',
            'img/ssb/samus.png',
            'img/ssb/sheik.png',
            'img/ssb/sonic.png',
            'img/ssb/yoshi.png',
            'img/ssb/zelda.png',
            'img/ssb/zsamus.png'
        ]
    },
    {
        name: 'Pokemon',
        description: 'Pokemon Characters',
        credit: 'FreePNGImg',
        url: 'https://www.freepngimg.com',
        cover: 'img/pokemon/cover.png',
        images: [
            'img/pokemon/1.png',
            'img/pokemon/2.png',
            'img/pokemon/3.png',
            'img/pokemon/4.png',
            'img/pokemon/5.png',
            'img/pokemon/6.png',
            'img/pokemon/7.png',
            'img/pokemon/8.png',
            'img/pokemon/9.png',
            'img/pokemon/10.png',
            'img/pokemon/11.png',
            'img/pokemon/12.png',
            'img/pokemon/13.png',
            'img/pokemon/14.png',
            'img/pokemon/15.png',
            'img/pokemon/16.png',
            'img/pokemon/17.png',
            'img/pokemon/18.png',
            'img/pokemon/19.png',
            'img/pokemon/20.png',
        ]
    },
    {
        name: 'Mammals',
        description: 'Match photos of mammals',
        credit: 'NC Zoo',
        url: 'http://nczoo.smugmug.com/',
        cover: 'http://i.imgur.com/GgXTN32b.jpg',
        images: [
            'http://i.imgur.com/YhfJA6Bb.jpg',
            'http://i.imgur.com/MkSQWEbb.jpg',
            'http://i.imgur.com/4VBD5ZWb.jpg',
            'http://i.imgur.com/OzVldvTb.jpg',
            'http://i.imgur.com/Cg0tPTNb.jpg',
            'http://i.imgur.com/mDNHdFyb.jpg',
            'http://i.imgur.com/Y8UyFfZb.jpg',
            'http://i.imgur.com/RQbd0O6b.jpg',
            'http://i.imgur.com/cc0K8eFb.jpg',
            'http://i.imgur.com/TddxeImb.jpg',
            'http://i.imgur.com/agbr33Mb.jpg',
            'http://i.imgur.com/JtunBw0b.jpg',
            'http://i.imgur.com/i2lQf8sb.jpg',
            'http://i.imgur.com/GkSqPtMb.jpg',
            'http://i.imgur.com/JyOt7Fib.jpg',
            'http://i.imgur.com/UZHWrw5b.jpg',
            'http://i.imgur.com/GgXTN32b.jpg',
            'http://i.imgur.com/3SRiv1ub.jpg',
            'http://i.imgur.com/qa9zFbtb.jpg',
            'http://i.imgur.com/0RdrDHxb.jpg',
            'http://i.imgur.com/K8AmxPpb.jpg',
            'http://i.imgur.com/63npqeVb.jpg',
            'http://i.imgur.com/AXMMYYPb.jpg',
            'http://i.imgur.com/GWN1NJ6b.jpg'
        ]
    },
    {
        name: 'Birds',
        description: 'Match photos of birds',
        credit: 'NC Zoo',
        url: 'http://nczoo.smugmug.com/',
        cover: 'http://i.imgur.com/rfSUStLb.jpg',
        images: [
            'http://i.imgur.com/JLANds8.jpg',
            'http://i.imgur.com/B3PjkO0.jpg',
            'http://i.imgur.com/wJnoyw0.jpg',
            'http://i.imgur.com/qTwDzOS.jpg',
            'http://i.imgur.com/EfLODeM.jpg',
            'http://i.imgur.com/HbPm7Hx.jpg',
            'http://i.imgur.com/zNA4lk0.jpg',
            'http://i.imgur.com/9JQck56.jpg',
            'http://i.imgur.com/qu2kGHd.jpg',
            'http://i.imgur.com/KgoAnhf.jpg',
            'http://i.imgur.com/PEeDfykb.jpg',
            'http://i.imgur.com/m1Eyje3b.jpg',
            'http://i.imgur.com/RNXB5WSb.jpg',
            'http://i.imgur.com/rfSUStLb.jpg',
            'http://i.imgur.com/2FFe3sqb.jpg',
            'http://i.imgur.com/LaNNSZBb.jpg'
        ]
    },
    {
        name: 'Reptiles',
        description: 'Match photos of reptiles',
        credit: 'NC Zoo',
        url: 'http://nczoo.smugmug.com/',
        cover: 'http://i.imgur.com/1jEPvOO.jpg',
        images: [
            'http://i.imgur.com/FIWbEc3.jpg',
            'http://i.imgur.com/PnrYQEY.jpg',
            'http://i.imgur.com/0OwApBB.jpg',
            'http://i.imgur.com/S4U0TfH.jpg',
            'http://i.imgur.com/1jEPvOO.jpg',
            'http://i.imgur.com/JZc1AXh.jpg',
            'http://i.imgur.com/F6iBZtx.jpg',
            'http://i.imgur.com/gah83dV.jpg',
            'http://i.imgur.com/q1GUgdo.jpg',
            'http://i.imgur.com/quEkyHT.jpg',
            'http://i.imgur.com/AF7Wm0y.jpg',
            'http://i.imgur.com/HWcJZXT.jpg'
        ]
    },
    {
        name: 'Flags of the World',
        description: 'Flags of the World',
        credit: 'Flagpedia',
        url: 'https://flagpedia.net/',
        cover: 'img/flags/cover.png',
        images: [
            'img/flags/ad.png',
            'img/flags/ae.png',
            'img/flags/af.png',
            'img/flags/ag.png',
            'img/flags/al.png',
            'img/flags/am.png',
            'img/flags/ao.png',
            'img/flags/ar.png',
            'img/flags/at.png',
            'img/flags/au.png',
            'img/flags/az.png',
            'img/flags/ba.png',
            'img/flags/bb.png',
            'img/flags/bd.png',
            'img/flags/be.png',
            'img/flags/bf.png',
            'img/flags/bg.png',
            'img/flags/bh.png',
            'img/flags/bi.png',
            'img/flags/bj.png',
            'img/flags/bn.png',
            'img/flags/bo.png',
            'img/flags/br.png',
            'img/flags/bs.png',
            'img/flags/bt.png',
            'img/flags/bw.png',
            'img/flags/by.png',
            'img/flags/bz.png',
            'img/flags/ca.png',
            'img/flags/cd.png',
            'img/flags/cf.png',
            'img/flags/cg.png',
            'img/flags/ch.png',
            'img/flags/ci.png',
            'img/flags/cl.png',
            'img/flags/cm.png',
            'img/flags/cn.png',
            'img/flags/co.png',
            'img/flags/cr.png',
            'img/flags/cu.png',
            'img/flags/cv.png',
            'img/flags/cy.png',
            'img/flags/cz.png',
            'img/flags/de.png',
            'img/flags/dj.png',
            'img/flags/dk.png',
            'img/flags/dm.png',
            'img/flags/do.png',
            'img/flags/dz.png',
            'img/flags/ec.png',
            'img/flags/ee.png',
            'img/flags/eg.png',
            'img/flags/eh.png',
            'img/flags/er.png',
            'img/flags/es.png',
            'img/flags/et.png',
            'img/flags/fi.png',
            'img/flags/fj.png',
            'img/flags/fm.png',
            'img/flags/fr.png',
            'img/flags/ga.png',
            'img/flags/gb.png',
            'img/flags/gd.png',
            'img/flags/ge.png',
            'img/flags/gh.png',
            'img/flags/gm.png',
            'img/flags/gn.png',
            'img/flags/gq.png',
            'img/flags/gr.png',
            'img/flags/gt.png',
            'img/flags/gw.png',
            'img/flags/gy.png',
            'img/flags/hn.png',
            'img/flags/hr.png',
            'img/flags/ht.png',
            'img/flags/hu.png',
            'img/flags/id.png',
            'img/flags/ie.png',
            'img/flags/il.png',
            'img/flags/in.png',
            'img/flags/iq.png',
            'img/flags/ir.png',
            'img/flags/is.png',
            'img/flags/it.png',
            'img/flags/jm.png',
            'img/flags/jo.png',
            'img/flags/jp.png',
            'img/flags/ke.png',
            'img/flags/kg.png',
            'img/flags/kh.png',
            'img/flags/ki.png',
            'img/flags/km.png',
            'img/flags/kn.png',
            'img/flags/kp.png',
            'img/flags/kr.png',
            'img/flags/ks.png',
            'img/flags/kw.png',
            'img/flags/kz.png',
            'img/flags/la.png',
            'img/flags/lb.png',
            'img/flags/lc.png',
            'img/flags/li.png',
            'img/flags/lk.png',
            'img/flags/lr.png',
            'img/flags/ls.png',
            'img/flags/lt.png',
            'img/flags/lu.png',
            'img/flags/lv.png',
            'img/flags/ly.png',
            'img/flags/ma.png',
            'img/flags/mc.png',
            'img/flags/md.png',
            'img/flags/me.png',
            'img/flags/mg.png',
            'img/flags/mh.png',
            'img/flags/mk.png',
            'img/flags/ml.png',
            'img/flags/mm.png',
            'img/flags/mn.png',
            'img/flags/mr.png',
            'img/flags/mt.png',
            'img/flags/mu.png',
            'img/flags/mv.png',
            'img/flags/mw.png',
            'img/flags/mx.png',
            'img/flags/my.png',
            'img/flags/mz.png',
            'img/flags/na.png',
            'img/flags/ne.png',
            'img/flags/ng.png',
            'img/flags/ni.png',
            'img/flags/nl.png',
            'img/flags/no.png',
            'img/flags/np.png',
            'img/flags/nr.png',
            'img/flags/nz.png',
            'img/flags/om.png',
            'img/flags/pa.png',
            'img/flags/pe.png',
            'img/flags/pg.png',
            'img/flags/ph.png',
            'img/flags/pk.png',
            'img/flags/pl.png',
            'img/flags/pt.png',
            'img/flags/pw.png',
            'img/flags/py.png',
            'img/flags/qa.png',
            'img/flags/ro.png',
            'img/flags/rs.png',
            'img/flags/ru.png',
            'img/flags/rw.png',
            'img/flags/sa.png',
            'img/flags/sb.png',
            'img/flags/sc.png',
            'img/flags/sd.png',
            'img/flags/se.png',
            'img/flags/sg.png',
            'img/flags/si.png',
            'img/flags/sk.png',
            'img/flags/sl.png',
            'img/flags/sm.png',
            'img/flags/sn.png',
            'img/flags/so.png',
            'img/flags/sr.png',
            'img/flags/st.png',
            'img/flags/sv.png',
            'img/flags/sy.png',
            'img/flags/sz.png',
            'img/flags/td.png',
            'img/flags/tg.png',
            'img/flags/th.png',
            'img/flags/tj.png',
            'img/flags/tl.png',
            'img/flags/tm.png',
            'img/flags/tn.png',
            'img/flags/to.png',
            'img/flags/tr.png',
            'img/flags/tt.png',
            'img/flags/tv.png',
            'img/flags/tw.png',
            'img/flags/tz.png',
            'img/flags/ua.png',
            'img/flags/ug.png',
            'img/flags/us.png',
            'img/flags/uy.png',
            'img/flags/uz.png',
            'img/flags/va.png',
            'img/flags/vc.png',
            'img/flags/ve.png',
            'img/flags/vn.png',
            'img/flags/vu.png',
            'img/flags/ws.png',
            'img/flags/ye.png',
            'img/flags/za.png',
            'img/flags/zm.png',
            'img/flags/zw.png',
        ]
    },
    {
        name: 'US State Flags',
        description: 'Flags of the United States',
        credit: 'Flagpedia',
        url: 'https://usa.flagpedia.net/',
        cover: 'img/flags/us.png',
        images: [
            'img/flags-us/ak.png',
            'img/flags-us/al.png',
            'img/flags-us/ar.png',
            'img/flags-us/az.png',
            'img/flags-us/ca.png',
            'img/flags-us/co.png',
            'img/flags-us/ct.png',
            'img/flags-us/de.png',
            'img/flags-us/fl.png',
            'img/flags-us/ga.png',
            'img/flags-us/hi.png',
            'img/flags-us/ia.png',
            'img/flags-us/id.png',
            'img/flags-us/il.png',
            'img/flags-us/in.png',
            'img/flags-us/ks.png',
            'img/flags-us/ky.png',
            'img/flags-us/la.png',
            'img/flags-us/ma.png',
            'img/flags-us/md.png',
            'img/flags-us/me.png',
            'img/flags-us/mi.png',
            'img/flags-us/mn.png',
            'img/flags-us/mo.png',
            'img/flags-us/ms.png',
            'img/flags-us/mt.png',
            'img/flags-us/nc.png',
            'img/flags-us/nd.png',
            'img/flags-us/ne.png',
            'img/flags-us/nh.png',
            'img/flags-us/nj.png',
            'img/flags-us/nm.png',
            'img/flags-us/nv.png',
            'img/flags-us/ny.png',
            'img/flags-us/oh.png',
            'img/flags-us/ok.png',
            'img/flags-us/or.png',
            'img/flags-us/pa.png',
            'img/flags-us/ri.png',
            'img/flags-us/sc.png',
            'img/flags-us/sd.png',
            'img/flags-us/tn.png',
            'img/flags-us/tx.png',
            'img/flags-us/ut.png',
            'img/flags-us/va.png',
            'img/flags-us/vt.png',
            'img/flags-us/wa.png',
            'img/flags-us/wi.png',
            'img/flags-us/wv.png',
            'img/flags-us/wy.png',
        ]
    }
];
